### ISSUE TITLE
Imp to Eclipse log cannot be resolved

### ISSUE THREAD

**Issue by dennyalice2010** [wangdani/epidemicSituation#1]
你好
   当我导入程序到Eclipse中时发生log cannot be resolved错误，我在pom文件中有加入Slf4j1.7.3
但问题还是没有解决，还请帮忙提示一下

**Comment by wangdani** [comment]
不用加Slf4j1.7.3
我的pom文件里有
<dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
   </dependency>
你报错的原因是eclipse里缺少lombok插件，下载一个lombok插件或者把eclipse换成idea即可

**Comment by dennyalice2010** [comment]
好的，感谢您的回复，我试一下

**Comment by dennyalice2010** [comment]
ok了，感谢，再请教一下，如果在您的项目基础上查看世界新冠的疫情状况，数据源的url还是同一个么？还需要注意啥？Java新手还望多指教

**Comment by wangdani** [comment]
我这个程序只能查看全国各省的疫情状况，不兼容其他国家的疫情状况，需要调用别的url

**Comment by dennyalice2010** [comment]
感谢

**Comment by dennyalice2010** [comment]
又要麻烦您，我运行时Console界面没有报错和警告，但是访问http://localhost:8081/wuhanyq/或http://localhost:8081/wuhanyq/yq.html时浏览器有提示404 错误，我看配置文件中的端口和名称都是对的呀，还请帮忙提示一下
感谢
--------------------------------

ICT /  王志強


天下事有难易乎?为之，则难者亦易矣;不为，则难者亦难矣。
Believe in the impossible and remove the improbable
坚信没有做不到的事情，忘记那些不可能的事情




----- 原始邮件 -----
发件人：wangdani <notifications@github.com>
收件人：wangdani/epidemicSituation <epidemicSituation@noreply.github.com>
抄送人：WangZhiQiang <wangzhiqiang2018@sina.com>,  Author <author@noreply.github.com>
主题：Re: [wangdani/epidemicSituation] Imp to Eclipse log cannot be resolved (#1)
日期：2020年03月24日 09点00分



我这个程序只能查看全国各省的疫情状况，不兼容其他国家的疫情状况，需要调用别的url

**Comment by wangdani** [comment]
我readme里面的演示示例你看一下，按照那个url改就行

**Comment by dennyalice2010** [comment]
收到，在Eclipes中已经调试出来，感谢提醒，继续学习，上次您提到的世界疫情的数据源url是啥？能告诉我一下么？
感谢
--------------------------------

ICT /  王志強


天下事有难易乎?为之，则难者亦易矣;不为，则难者亦难矣。
Believe in the impossible and remove the improbable
坚信没有做不到的事情，忘记那些不可能的事情




----- 原始邮件 -----
发件人：wangdani <notifications@github.com>
收件人：wangdani/epidemicSituation <epidemicSituation@noreply.github.com>
抄送人：WangZhiQiang <wangzhiqiang2018@sina.com>,  State change <state_change@noreply.github.com>
主题：Re: [wangdani/epidemicSituation] Imp to Eclipse log cannot be resolved (#1)
日期：2020年03月25日 11点42分



我readme里面的演示示例你看一下，按照那个url改就行

**Comment by wangdani** [comment]
我没有世界疫情的数据源

**Comment by dennyalice2010** [comment]
了解，感谢您

--------------------------------

ICT /  王志強


天下事有难易乎?为之，则难者亦易矣;不为，则难者亦难矣。
Believe in the impossible and remove the improbable
坚信没有做不到的事情，忘记那些不可能的事情




----- 原始邮件 -----
发件人：wangdani <notifications@github.com>
收件人：wangdani/epidemicSituation <epidemicSituation@noreply.github.com>
抄送人：WangZhiQiang <wangzhiqiang2018@sina.com>,  State change <state_change@noreply.github.com>
主题：Re: [wangdani/epidemicSituation] Imp to Eclipse log cannot be resolved (#1)
日期：2020年03月25日 13点18分



我没有世界疫情的数据源
